-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'max-gamma = 100' has no enclosing section

-- TODO: manual review — unknown section 'profile {' on line 3

-- TODO: manual review — unknown section 'profile {' on line 8
