theme = {
    color_schema = "/usr/share/themes/Colloid-Purple-Dark-Catppuccin"
    icon_theme = "Colloid-Purple-Catppuccin-Dark"
    style = "kvantum-dark"
    font_fixed = "JetBrainsMono Nerd Font"
    font_fixed_size = 12
    font = "Manrope ExtraLight"
    font_size = 12
}

