theme {
    color_scheme = "/home/sudacode/.local/share/color-schemes/CatppuccinMacchiatoMauve.colors"
    icon_theme = "Colloid-Purple-Catppuccin-Dark"
    style = "kvantum-dark"
    font_fixed = "JetBrainsMono Nerd Font"
    font_fixed_size = 12
    font = "Manrope ExtraLight"
    font_size = 12
}

