-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local rosewater = "rgb(f4dbd6)"
local rosewaterAlpha = "f4dbd6"

local flamingo = "rgb(f0c6c6)"
local flamingoAlpha = "f0c6c6"

local pink = "rgb(f5bde6)"
local pinkAlpha = "f5bde6"

local mauve = "rgb(c6a0f6)"
local mauveAlpha = "c6a0f6"

local red = "rgb(ed8796)"
local redAlpha = "ed8796"

local maroon = "rgb(ee99a0)"
local maroonAlpha = "ee99a0"

local peach = "rgb(f5a97f)"
local peachAlpha = "f5a97f"

local yellow = "rgb(eed49f)"
local yellowAlpha = "eed49f"

local green = "rgb(a6da95)"
local greenAlpha = "a6da95"

local teal = "rgb(8bd5ca)"
local tealAlpha = "8bd5ca"

local sky = "rgb(91d7e3)"
local skyAlpha = "91d7e3"

local sapphire = "rgb(7dc4e4)"
local sapphireAlpha = "7dc4e4"

local blue = "rgb(8aadf4)"
local blueAlpha = "8aadf4"

local lavender = "rgb(b7bdf8)"
local lavenderAlpha = "b7bdf8"

local text = "rgb(cad3f5)"
local textAlpha = "cad3f5"

local subtext1 = "rgb(b8c0e0)"
local subtext1Alpha = "b8c0e0"

local subtext0 = "rgb(a5adcb)"
local subtext0Alpha = "a5adcb"

local overlay2 = "rgb(939ab7)"
local overlay2Alpha = "939ab7"

local overlay1 = "rgb(8087a2)"
local overlay1Alpha = "8087a2"

local overlay0 = "rgb(6e738d)"
local overlay0Alpha = "6e738d"

local surface2 = "rgb(5b6078)"
local surface2Alpha = "5b6078"

local surface1 = "rgb(494d64)"
local surface1Alpha = "494d64"

local surface0 = "rgb(363a4f)"
local surface0Alpha = "363a4f"

local base = "rgb(24273a)"
local baseAlpha = "24273a"

local mantle = "rgb(1e2030)"
local mantleAlpha = "1e2030"

local crust = "rgb(181926)"
local crustAlpha = 181926
