return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"c",
				"lua",
				"vim",
				"vimdoc",
				"query",
				"cpp",
				"python",
				"bash",
				"sql",
				"yaml",
				"toml",
				"dockerfile",
				"gitcommit",
				"gitignore",
				"html",
				"css",
				"javascript",
				"typescript",
				"rust",
				"go",
				"gowork",
				"gotmpl",
				"json",
				"regex",
				"latex",
				"comment",
				"cmake",
				"graphql",
				"haskell",
				"java",
				"php",
				"ruby",
				"vue",
				"markdown",
				"markdown_inline",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
