require("core.lazy")
vim.cmd("colorscheme catppuccin")
require("core.keymaps")
require("core.autocmds")
require("core.highlights")
-- require("core.lsp-notifications")
require("utils.extensions")
require("utils.telescope_extra").setup()
require("utils.functions.git_paste").setup({ telescope_key = "<leader>pg" })
require("utils.treesitter.parsers.hyprlang")
require("utils.hyprland.lsp")
